######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 10 16:07:17 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += game.h main_window.h square.h
SOURCES += game.cpp main.cpp main_window.cpp square.cpp
